### ISSUE TITLE
期待支持多维表格的字段描述

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/TalkBase#6]
<img width="821" alt="image" src="https://github.com/ConnectAI-E/TalkBase/assets/50035229/d38eac44-2a1b-40ee-9203-95aa6aa12b0a">

**Comment by larkway** [comment]
多维表格还未暴露获取字段描述的接口，等待官方api~

**Comment by terrycarter1985** [comment]
收到
